/*
ARRAY :ARRAYS IS A LIST OF ELEMENTS OF THE SAME TYPE PLACES IN A CONTIGUOUS MEMORY LOCATION

->INDEX START WITH THE POSITION 0 TO N NUMBER ARRAYS 
->ARRAYS ARE USED TO STORE MULTIPLE VALUES IN A SINGLE VARIABLE, INSTEAD OF DECLARING SEPARATE VARIABLES FOR EACH VALUE.
->ARRAYS ARE USED TO STORE MULTIPLE VALUES OF THE SAME TYPE.
->ARRAYS ARE FIXED IN SIZE, MEANING THAT ONCE AN ARRAY IS CREATED, ITS SIZE CANNOT BE CHANGED.
->ARRAYS CAN BE OF PRIMITIVE DATA TYPES OR OBJECTS.
->ARRAYS CAN BE SINGLE DIMENSIONAL OR MULTI DIMENSIONAL.
->ARRAYS ARE USED TO STORE DATA IN A CONTIGUOUS MEMORY LOCATION.
->ARRAYS ARE USED TO STORE DATA IN A CONTIGUOUS MEMORY LOCATION, WHICH MAKES IT EFFICIENT FOR ACCESSING ELEMENTS.
->ARRAYS ARE IMPLEMENTED USING INDEXES, WHICH ALLOWS FOR QUICK ACCESS TO ELEMENTS.

OPERATION IN ARRAYS:
1. Traversing: Accessing each element of the array.
2. Insertion: Adding an element at a specific index in the array.
3. Deletion: Removing an element from a specific index in the array.

(1)CREATE AN ARRAY:
SYNTAX:
           data_type[] array_name = new data_type[size];
for example:

(i) int marks[]= new int[50];                              ; SIZE OF THIS ARRAY IS 50, IT CAN STORE 50 ELEMENTS OF INTEGER TYPE.
(ii)int numbers[]={1,2,3};                                 ; SIZE OF THIS ARRAY IS 3, IT CAN STORE 3 ELEMENTS OF INTEGER TYPE.
(iii)int morenumber[] ={4,5,6};                            ; SIZE OF THIS ARRAY IS 3, IT CAN STORE 3 ELEMENTS OF INTEGER TYPE.
(iv) String fruitnames[] = {"Apple","Banana","Mango"};     ; SIZE OF THIS ARRAY IS 3, IT CAN STORE 3 ELEMENTS OF STRING TYPE.
 */